import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import {
  Akzidenz,
  Akzidenzlc,
  Akzidenzpc,
  SaolDisplay,
  SaolDisplayR,
} from "@/font_utils/customFonts";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Akzidenz.variable} ${SaolDisplay.variable} 
      ${Akzidenzpc.variable} 
      ${SaolDisplayR.variable} ${Akzidenzlc.variable}`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
