import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";

import {
  Akzidenregular,
  Akzidenzlc,
  Akzidenzpc,
  Apercu,
  SaolDisplay,
  SaolDisplayR,
  SaolDisplayl,
} from "@/font_utils/customFonts";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Wrapper from "./Shared/Wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Akzidenregular.variable} ${SaolDisplay.variable} 
      ${Akzidenzpc.variable} 
      ${SaolDisplayR.variable} ${Akzidenzlc.variable} ${Apercu.variable} ${SaolDisplayl.variable}`}
      >
        <Wrapper>
          <Navbar />
          {children}
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
